### ISSUE TITLE
docs: improve README.md, add Code of Conduct, Contributing, License, Security Policy, Issue Templates, Pull Request Templates

### ISSUE THREAD

**Issue by farisfaikar** [farisfaikar/wayry#14]
## Docs to add
- [x] Improve README.md
- [x] Code of Conduct
- [x] Contributing
- [x] License
- [ ] Security Policy (optional)
- [x] Issue Templates (optional)
- [x] Pull Request Templates (optional)

This is a non-code issue, so it should be a good PR newcomers 😇

**Comment by SartHak-0-Sach** [comment]
Hi @farisfaikar I would love to work on this issue, please assign me this and allow me to contribute to it

**Comment by farisfaikar** [comment]
Sure thing! Happy writing 🤩

**Comment by SartHak-0-Sach** [comment]
Ok thanks a lot😇

**Comment by Brijeshthummar02** [comment]
@farisfaikar , @SartHak-0-Sach  as there are so many things to add, add me also to the task my pr are ready.

**Comment by farisfaikar** [comment]
@Brijeshthummar02 sure thing! This is indeed an issue that would best be worked on by multiple people

**Comment by SartHak-0-Sach** [comment]
I am planning to create separate pull request for improving README file, and a separate one for other documents because the way I am planning to redesign the README is open to interpretation on how you imagine your README file to look like, so I don't want my whole pull request involving several contributions to be halted just because of a single document.

Hope you understand @farisfaikar

**Comment by farisfaikar** [comment]
@SartHak-0-Sach Yes! I think that's the best way of working on the docs. One pull request for every docs that I've listed would be a good way to do things. Carry on!

**Comment by SartHak-0-Sach** [comment]
Hi @farisfaikar I have added all files you asked for to the best of my knowledge, please review my pull request and suggest if any changes are required
